-- ─── CodingSharks Database Schema ────────────────────────────────────────────
-- Run this SQL in your Supabase SQL Editor
-- Go to: Supabase Dashboard → SQL Editor → New Query → paste and run
-- (Admin Users, Blog, and Blog Tag tables have been removed)
